<!-- NEK NENG CI 4 MODEL KUI NGGO NGAWE FUNCITION -->
<!-- CONFIG ROUTE DINGGO NGATUR HALAMAN -->
<!-- CONTROLLER NEK RA SALAH MENGKO SEKO VIEWS KUI DI CELOK NENG CONTROLLER ANGGO RETURN BAR WI SEK FUNCITION NENG MODEL KUI DI CELOK -->